// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Helper.Localization.Resx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources_es {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_es() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Helper.Localization.Resx.AppResources.es", typeof(AppResources_es).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string add_parcel {
            get {
                return ResourceManager.GetString("add_parcel", resourceCulture);
            }
        }
        
        public static string agronomical_cycle {
            get {
                return ResourceManager.GetString("agronomical_cycle", resourceCulture);
            }
        }
        
        public static string agronomical_cycle_1 {
            get {
                return ResourceManager.GetString("agronomical_cycle_1", resourceCulture);
            }
        }
        
        public static string agronomical_cycle_2 {
            get {
                return ResourceManager.GetString("agronomical_cycle_2", resourceCulture);
            }
        }
        
        public static string agronomic_cycle_type {
            get {
                return ResourceManager.GetString("agronomic_cycle_type", resourceCulture);
            }
        }
        
        public static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        public static string april {
            get {
                return ResourceManager.GetString("april", resourceCulture);
            }
        }
        
        public static string august {
            get {
                return ResourceManager.GetString("august", resourceCulture);
            }
        }
        
        public static string btn_choose_location {
            get {
                return ResourceManager.GetString("btn_choose_location", resourceCulture);
            }
        }
        
        public static string btn_save_and_new {
            get {
                return ResourceManager.GetString("btn_save_and_new", resourceCulture);
            }
        }
        
        public static string btn_save_and_new1 {
            get {
                return ResourceManager.GetString("btn_save_and_new1", resourceCulture);
            }
        }
        
        public static string cdd {
            get {
                return ResourceManager.GetString("cdd", resourceCulture);
            }
        }
        
        public static string coordinator {
            get {
                return ResourceManager.GetString("coordinator", resourceCulture);
            }
        }
        
        public static string crop_types_1 {
            get {
                return ResourceManager.GetString("crop_types_1", resourceCulture);
            }
        }
        
        public static string crop_types_10 {
            get {
                return ResourceManager.GetString("crop_types_10", resourceCulture);
            }
        }
        
        public static string crop_types_11 {
            get {
                return ResourceManager.GetString("crop_types_11", resourceCulture);
            }
        }
        
        public static string crop_types_12 {
            get {
                return ResourceManager.GetString("crop_types_12", resourceCulture);
            }
        }
        
        public static string crop_types_13 {
            get {
                return ResourceManager.GetString("crop_types_13", resourceCulture);
            }
        }
        
        public static string crop_types_14 {
            get {
                return ResourceManager.GetString("crop_types_14", resourceCulture);
            }
        }
        
        public static string crop_types_15 {
            get {
                return ResourceManager.GetString("crop_types_15", resourceCulture);
            }
        }
        
        public static string crop_types_16 {
            get {
                return ResourceManager.GetString("crop_types_16", resourceCulture);
            }
        }
        
        public static string crop_types_17 {
            get {
                return ResourceManager.GetString("crop_types_17", resourceCulture);
            }
        }
        
        public static string crop_types_18 {
            get {
                return ResourceManager.GetString("crop_types_18", resourceCulture);
            }
        }
        
        public static string crop_types_19 {
            get {
                return ResourceManager.GetString("crop_types_19", resourceCulture);
            }
        }
        
        public static string crop_types_2 {
            get {
                return ResourceManager.GetString("crop_types_2", resourceCulture);
            }
        }
        
        public static string crop_types_3 {
            get {
                return ResourceManager.GetString("crop_types_3", resourceCulture);
            }
        }
        
        public static string crop_types_4 {
            get {
                return ResourceManager.GetString("crop_types_4", resourceCulture);
            }
        }
        
        public static string crop_types_5 {
            get {
                return ResourceManager.GetString("crop_types_5", resourceCulture);
            }
        }
        
        public static string crop_types_6 {
            get {
                return ResourceManager.GetString("crop_types_6", resourceCulture);
            }
        }
        
        public static string crop_types_7 {
            get {
                return ResourceManager.GetString("crop_types_7", resourceCulture);
            }
        }
        
        public static string crop_types_8 {
            get {
                return ResourceManager.GetString("crop_types_8", resourceCulture);
            }
        }
        
        public static string crop_types_9 {
            get {
                return ResourceManager.GetString("crop_types_9", resourceCulture);
            }
        }
        
        public static string cycle {
            get {
                return ResourceManager.GetString("cycle", resourceCulture);
            }
        }
        
        public static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        public static string december {
            get {
                return ResourceManager.GetString("december", resourceCulture);
            }
        }
        
        public static string degrees_celsius {
            get {
                return ResourceManager.GetString("degrees_celsius", resourceCulture);
            }
        }
        
        public static string desc {
            get {
                return ResourceManager.GetString("desc", resourceCulture);
            }
        }
        
        public static string details {
            get {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }
        
        public static string detc {
            get {
                return ResourceManager.GetString("detc", resourceCulture);
            }
        }
        
        public static string dht {
            get {
                return ResourceManager.GetString("dht", resourceCulture);
            }
        }
        
        public static string direction_unit {
            get {
                return ResourceManager.GetString("direction_unit", resourceCulture);
            }
        }
        
        public static string direction_unit_short {
            get {
                return ResourceManager.GetString("direction_unit_short", resourceCulture);
            }
        }
        
        public static string dlt {
            get {
                return ResourceManager.GetString("dlt", resourceCulture);
            }
        }
        
        public static string dp {
            get {
                return ResourceManager.GetString("dp", resourceCulture);
            }
        }
        
        public static string dsr {
            get {
                return ResourceManager.GetString("dsr", resourceCulture);
            }
        }
        
        public static string end {
            get {
                return ResourceManager.GetString("end", resourceCulture);
            }
        }
        
        public static string evapotranspiration_unit {
            get {
                return ResourceManager.GetString("evapotranspiration_unit", resourceCulture);
            }
        }
        
        public static string evapotranspiration_unit_hour {
            get {
                return ResourceManager.GetString("evapotranspiration_unit_hour", resourceCulture);
            }
        }
        
        public static string evapotranspiration_unit_hour_short {
            get {
                return ResourceManager.GetString("evapotranspiration_unit_hour_short", resourceCulture);
            }
        }
        
        public static string evapotranspiration_unit_short {
            get {
                return ResourceManager.GetString("evapotranspiration_unit_short", resourceCulture);
            }
        }
        
        public static string february {
            get {
                return ResourceManager.GetString("february", resourceCulture);
            }
        }
        
        public static string filter {
            get {
                return ResourceManager.GetString("filter", resourceCulture);
            }
        }
        
        public static string gdd {
            get {
                return ResourceManager.GetString("gdd", resourceCulture);
            }
        }
        
        public static string hd {
            get {
                return ResourceManager.GetString("hd", resourceCulture);
            }
        }
        
        public static string hdd {
            get {
                return ResourceManager.GetString("hdd", resourceCulture);
            }
        }
        
        public static string hesc {
            get {
                return ResourceManager.GetString("hesc", resourceCulture);
            }
        }
        
        public static string hetc {
            get {
                return ResourceManager.GetString("hetc", resourceCulture);
            }
        }
        
        public static string hint_additional_information {
            get {
                return ResourceManager.GetString("hint_additional_information", resourceCulture);
            }
        }
        
        public static string hint_agronomical_cycle {
            get {
                return ResourceManager.GetString("hint_agronomical_cycle", resourceCulture);
            }
        }
        
        public static string hint_area {
            get {
                return ResourceManager.GetString("hint_area", resourceCulture);
            }
        }
        
        public static string hint_crop {
            get {
                return ResourceManager.GetString("hint_crop", resourceCulture);
            }
        }
        
        public static string hint_cultivar {
            get {
                return ResourceManager.GetString("hint_cultivar", resourceCulture);
            }
        }
        
        public static string hint_cultivar_placeholder {
            get {
                return ResourceManager.GetString("hint_cultivar_placeholder", resourceCulture);
            }
        }
        
        public static string hint_firstname_lastname {
            get {
                return ResourceManager.GetString("hint_firstname_lastname", resourceCulture);
            }
        }
        
        public static string hint_irrigation {
            get {
                return ResourceManager.GetString("hint_irrigation", resourceCulture);
            }
        }
        
        public static string hint_notifications {
            get {
                return ResourceManager.GetString("hint_notifications", resourceCulture);
            }
        }
        
        public static string hint_notification_received {
            get {
                return ResourceManager.GetString("hint_notification_received", resourceCulture);
            }
        }
        
        public static string hint_other_technology_used {
            get {
                return ResourceManager.GetString("hint_other_technology_used", resourceCulture);
            }
        }
        
        public static string hint_parcel_name {
            get {
                return ResourceManager.GetString("hint_parcel_name", resourceCulture);
            }
        }
        
        public static string hint_parcel_name_1 {
            get {
                return ResourceManager.GetString("hint_parcel_name_1", resourceCulture);
            }
        }
        
        public static string hint_performance {
            get {
                return ResourceManager.GetString("hint_performance", resourceCulture);
            }
        }
        
        public static string hint_pesticide_date {
            get {
                return ResourceManager.GetString("hint_pesticide_date", resourceCulture);
            }
        }
        
        public static string hint_pesticide_product {
            get {
                return ResourceManager.GetString("hint_pesticide_product", resourceCulture);
            }
        }
        
        public static string hint_pesticide_product_placeholder {
            get {
                return ResourceManager.GetString("hint_pesticide_product_placeholder", resourceCulture);
            }
        }
        
        public static string hint_planting_date {
            get {
                return ResourceManager.GetString("hint_planting_date", resourceCulture);
            }
        }
        
        public static string hint_producer_name {
            get {
                return ResourceManager.GetString("hint_producer_name", resourceCulture);
            }
        }
        
        public static string hint_technologies_used {
            get {
                return ResourceManager.GetString("hint_technologies_used", resourceCulture);
            }
        }
        
        public static string hint_technology_other {
            get {
                return ResourceManager.GetString("hint_technology_other", resourceCulture);
            }
        }
        
        public static string hint_user_at_parcel {
            get {
                return ResourceManager.GetString("hint_user_at_parcel", resourceCulture);
            }
        }
        
        public static string hint_year {
            get {
                return ResourceManager.GetString("hint_year", resourceCulture);
            }
        }
        
        public static string hourly_radiation_unit {
            get {
                return ResourceManager.GetString("hourly_radiation_unit", resourceCulture);
            }
        }
        
        public static string hourly_radiation_unit_short {
            get {
                return ResourceManager.GetString("hourly_radiation_unit_short", resourceCulture);
            }
        }
        
        public static string hp {
            get {
                return ResourceManager.GetString("hp", resourceCulture);
            }
        }
        
        public static string hsr {
            get {
                return ResourceManager.GetString("hsr", resourceCulture);
            }
        }
        
        public static string ht {
            get {
                return ResourceManager.GetString("ht", resourceCulture);
            }
        }
        
        public static string hub {
            get {
                return ResourceManager.GetString("hub", resourceCulture);
            }
        }
        
        public static string hwd {
            get {
                return ResourceManager.GetString("hwd", resourceCulture);
            }
        }
        
        public static string hws {
            get {
                return ResourceManager.GetString("hws", resourceCulture);
            }
        }
        
        public static string institution {
            get {
                return ResourceManager.GetString("institution", resourceCulture);
            }
        }
        
        public static string irrigation_type_1 {
            get {
                return ResourceManager.GetString("irrigation_type_1", resourceCulture);
            }
        }
        
        public static string irrigation_type_2 {
            get {
                return ResourceManager.GetString("irrigation_type_2", resourceCulture);
            }
        }
        
        public static string irrigation_type_3 {
            get {
                return ResourceManager.GetString("irrigation_type_3", resourceCulture);
            }
        }
        
        public static string january {
            get {
                return ResourceManager.GetString("january", resourceCulture);
            }
        }
        
        public static string july {
            get {
                return ResourceManager.GetString("july", resourceCulture);
            }
        }
        
        public static string june {
            get {
                return ResourceManager.GetString("june", resourceCulture);
            }
        }
        
        public static string last_modification {
            get {
                return ResourceManager.GetString("last_modification", resourceCulture);
            }
        }
        
        public static string lat {
            get {
                return ResourceManager.GetString("lat", resourceCulture);
            }
        }
        
        public static string lng {
            get {
                return ResourceManager.GetString("lng", resourceCulture);
            }
        }
        
        public static string location {
            get {
                return ResourceManager.GetString("location", resourceCulture);
            }
        }
        
        public static string location1 {
            get {
                return ResourceManager.GetString("location1", resourceCulture);
            }
        }
        
        public static string march {
            get {
                return ResourceManager.GetString("march", resourceCulture);
            }
        }
        
        public static string may {
            get {
                return ResourceManager.GetString("may", resourceCulture);
            }
        }
        
        public static string millimeters {
            get {
                return ResourceManager.GetString("millimeters", resourceCulture);
            }
        }
        
        public static string millimeters_unit {
            get {
                return ResourceManager.GetString("millimeters_unit", resourceCulture);
            }
        }
        
        public static string november {
            get {
                return ResourceManager.GetString("november", resourceCulture);
            }
        }
        
        public static string october {
            get {
                return ResourceManager.GetString("october", resourceCulture);
            }
        }
        
        public static string optional_information {
            get {
                return ResourceManager.GetString("optional_information", resourceCulture);
            }
        }
        
        public static string page_title_add_parcel {
            get {
                return ResourceManager.GetString("page_title_add_parcel", resourceCulture);
            }
        }
        
        public static string page_title_benchmarking {
            get {
                return ResourceManager.GetString("page_title_benchmarking", resourceCulture);
            }
        }
        
        public static string page_title_links {
            get {
                return ResourceManager.GetString("page_title_links", resourceCulture);
            }
        }
        
        public static string page_title_login {
            get {
                return ResourceManager.GetString("page_title_login", resourceCulture);
            }
        }
        
        public static string page_title_main {
            get {
                return ResourceManager.GetString("page_title_main", resourceCulture);
            }
        }
        
        public static string page_title_map {
            get {
                return ResourceManager.GetString("page_title_map", resourceCulture);
            }
        }
        
        public static string page_title_notifications {
            get {
                return ResourceManager.GetString("page_title_notifications", resourceCulture);
            }
        }
        
        public static string page_title_parcels_overview {
            get {
                return ResourceManager.GetString("page_title_parcels_overview", resourceCulture);
            }
        }
        
        public static string page_title_parcel_add_information {
            get {
                return ResourceManager.GetString("page_title_parcel_add_information", resourceCulture);
            }
        }
        
        public static string page_title_parcel_benchmarking {
            get {
                return ResourceManager.GetString("page_title_parcel_benchmarking", resourceCulture);
            }
        }
        
        public static string page_title_parcel_details {
            get {
                return ResourceManager.GetString("page_title_parcel_details", resourceCulture);
            }
        }
        
        public static string page_title_parcel_page {
            get {
                return ResourceManager.GetString("page_title_parcel_page", resourceCulture);
            }
        }
        
        public static string page_title_parcel_weather {
            get {
                return ResourceManager.GetString("page_title_parcel_weather", resourceCulture);
            }
        }
        
        public static string page_title_parcel_windows_of_opportunity {
            get {
                return ResourceManager.GetString("page_title_parcel_windows_of_opportunity", resourceCulture);
            }
        }
        
        public static string page_title_register {
            get {
                return ResourceManager.GetString("page_title_register", resourceCulture);
            }
        }
        
        public static string page_title_weather {
            get {
                return ResourceManager.GetString("page_title_weather", resourceCulture);
            }
        }
        
        public static string page_title_welcome {
            get {
                return ResourceManager.GetString("page_title_welcome", resourceCulture);
            }
        }
        
        public static string plot {
            get {
                return ResourceManager.GetString("plot", resourceCulture);
            }
        }
        
        public static string precipitation {
            get {
                return ResourceManager.GetString("precipitation", resourceCulture);
            }
        }
        
        public static string production_type {
            get {
                return ResourceManager.GetString("production_type", resourceCulture);
            }
        }
        
        public static string radiation_unit {
            get {
                return ResourceManager.GetString("radiation_unit", resourceCulture);
            }
        }
        
        public static string radiation_unit_short {
            get {
                return ResourceManager.GetString("radiation_unit_short", resourceCulture);
            }
        }
        
        public static string register_email {
            get {
                return ResourceManager.GetString("register_email", resourceCulture);
            }
        }
        
        public static string register_email_empty {
            get {
                return ResourceManager.GetString("register_email_empty", resourceCulture);
            }
        }
        
        public static string register_email_invalid {
            get {
                return ResourceManager.GetString("register_email_invalid", resourceCulture);
            }
        }
        
        public static string register_password {
            get {
                return ResourceManager.GetString("register_password", resourceCulture);
            }
        }
        
        public static string register_password_empty {
            get {
                return ResourceManager.GetString("register_password_empty", resourceCulture);
            }
        }
        
        public static string register_password_verification {
            get {
                return ResourceManager.GetString("register_password_verification", resourceCulture);
            }
        }
        
        public static string register_password_verification_empty {
            get {
                return ResourceManager.GetString("register_password_verification_empty", resourceCulture);
            }
        }
        
        public static string register_password_verification_fail {
            get {
                return ResourceManager.GetString("register_password_verification_fail", resourceCulture);
            }
        }
        
        public static string register_username {
            get {
                return ResourceManager.GetString("register_username", resourceCulture);
            }
        }
        
        public static string register_username_empty {
            get {
                return ResourceManager.GetString("register_username_empty", resourceCulture);
            }
        }
        
        public static string rh {
            get {
                return ResourceManager.GetString("rh", resourceCulture);
            }
        }
        
        public static string s {
            get {
                return ResourceManager.GetString("s", resourceCulture);
            }
        }
        
        public static string september {
            get {
                return ResourceManager.GetString("september", resourceCulture);
            }
        }
        
        public static string solar_radiation {
            get {
                return ResourceManager.GetString("solar_radiation", resourceCulture);
            }
        }
        
        public static string speed_unit {
            get {
                return ResourceManager.GetString("speed_unit", resourceCulture);
            }
        }
        
        public static string speed_unit_short {
            get {
                return ResourceManager.GetString("speed_unit_short", resourceCulture);
            }
        }
        
        public static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        public static string surface {
            get {
                return ResourceManager.GetString("surface", resourceCulture);
            }
        }
        
        public static string technician {
            get {
                return ResourceManager.GetString("technician", resourceCulture);
            }
        }
        
        public static string technologies_used {
            get {
                return ResourceManager.GetString("technologies_used", resourceCulture);
            }
        }
        
        public static string technology_1 {
            get {
                return ResourceManager.GetString("technology_1", resourceCulture);
            }
        }
        
        public static string technology_2 {
            get {
                return ResourceManager.GetString("technology_2", resourceCulture);
            }
        }
        
        public static string technology_3 {
            get {
                return ResourceManager.GetString("technology_3", resourceCulture);
            }
        }
        
        public static string technology_4 {
            get {
                return ResourceManager.GetString("technology_4", resourceCulture);
            }
        }
        
        public static string technology_5 {
            get {
                return ResourceManager.GetString("technology_5", resourceCulture);
            }
        }
        
        public static string technology_6 {
            get {
                return ResourceManager.GetString("technology_6", resourceCulture);
            }
        }
        
        public static string technology_7 {
            get {
                return ResourceManager.GetString("technology_7", resourceCulture);
            }
        }
        
        public static string technology_8 {
            get {
                return ResourceManager.GetString("technology_8", resourceCulture);
            }
        }
        
        public static string temperature {
            get {
                return ResourceManager.GetString("temperature", resourceCulture);
            }
        }
        
        public static string trainer {
            get {
                return ResourceManager.GetString("trainer", resourceCulture);
            }
        }
        
        public static string unit {
            get {
                return ResourceManager.GetString("unit", resourceCulture);
            }
        }
        
        public static string unit_celsius {
            get {
                return ResourceManager.GetString("unit_celsius", resourceCulture);
            }
        }
        
        public static string unit_hectares {
            get {
                return ResourceManager.GetString("unit_hectares", resourceCulture);
            }
        }
        
        public static string unit_performance {
            get {
                return ResourceManager.GetString("unit_performance", resourceCulture);
            }
        }
        
        public static string year {
            get {
                return ResourceManager.GetString("year", resourceCulture);
            }
        }
    }
}
