//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helper.Localization.Resx {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Helper.Localization.Resx.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregue parcela.
        /// </summary>
        public static string add_parcel {
            get {
                return ResourceManager.GetString("add_parcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de ciclo agronómico.
        /// </summary>
        public static string agronomic_cycle_type {
            get {
                return ResourceManager.GetString("agronomic_cycle_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciclo agronómico.
        /// </summary>
        public static string agronomical_cycle {
            get {
                return ResourceManager.GetString("agronomical_cycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primavera-Verano.
        /// </summary>
        public static string agronomical_cycle_1 {
            get {
                return ResourceManager.GetString("agronomical_cycle_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otoño-Invierno.
        /// </summary>
        public static string agronomical_cycle_2 {
            get {
                return ResourceManager.GetString("agronomical_cycle_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to México Produce!.
        /// </summary>
        public static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abril.
        /// </summary>
        public static string april {
            get {
                return ResourceManager.GetString("april", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agosto.
        /// </summary>
        public static string august {
            get {
                return ResourceManager.GetString("august", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione el tipo de datos.
        /// </summary>
        public static string bem_data_type {
            get {
                return ResourceManager.GetString("bem_data_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información comparativa.
        /// </summary>
        public static string benchmarking {
            get {
                return ResourceManager.GetString("benchmarking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtener la ubicación de la parcela (GPS).
        /// </summary>
        public static string btn_choose_location {
            get {
                return ResourceManager.GetString("btn_choose_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string btn_get_location {
            get {
                return ResourceManager.GetString("btn_get_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomar una foto.
        /// </summary>
        public static string btn_photo {
            get {
                return ResourceManager.GetString("btn_photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string btn_save_and_new {
            get {
                return ResourceManager.GetString("btn_save_and_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar y añadir otra(o).
        /// </summary>
        public static string btn_save_and_new1 {
            get {
                return ResourceManager.GetString("btn_save_and_new1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendario.
        /// </summary>
        public static string calendar {
            get {
                return ResourceManager.GetString("calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grados-día de enfriamiento.
        /// </summary>
        public static string cdd {
            get {
                return ResourceManager.GetString("cdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinador.
        /// </summary>
        public static string coordinator {
            get {
                return ResourceManager.GetString("coordinator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maíz.
        /// </summary>
        public static string crop_types_1 {
            get {
                return ResourceManager.GetString("crop_types_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amaranto.
        /// </summary>
        public static string crop_types_10 {
            get {
                return ResourceManager.GetString("crop_types_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arroz.
        /// </summary>
        public static string crop_types_11 {
            get {
                return ResourceManager.GetString("crop_types_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canola.
        /// </summary>
        public static string crop_types_12 {
            get {
                return ResourceManager.GetString("crop_types_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartamo.
        /// </summary>
        public static string crop_types_13 {
            get {
                return ResourceManager.GetString("crop_types_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calabacín.
        /// </summary>
        public static string crop_types_14 {
            get {
                return ResourceManager.GetString("crop_types_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garbanzo.
        /// </summary>
        public static string crop_types_15 {
            get {
                return ResourceManager.GetString("crop_types_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haba.
        /// </summary>
        public static string crop_types_16 {
            get {
                return ResourceManager.GetString("crop_types_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soya.
        /// </summary>
        public static string crop_types_17 {
            get {
                return ResourceManager.GetString("crop_types_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ninguno.
        /// </summary>
        public static string crop_types_18 {
            get {
                return ResourceManager.GetString("crop_types_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otro.
        /// </summary>
        public static string crop_types_19 {
            get {
                return ResourceManager.GetString("crop_types_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cebada.
        /// </summary>
        public static string crop_types_2 {
            get {
                return ResourceManager.GetString("crop_types_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frijol.
        /// </summary>
        public static string crop_types_3 {
            get {
                return ResourceManager.GetString("crop_types_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigo.
        /// </summary>
        public static string crop_types_4 {
            get {
                return ResourceManager.GetString("crop_types_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triticale.
        /// </summary>
        public static string crop_types_5 {
            get {
                return ResourceManager.GetString("crop_types_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorgo.
        /// </summary>
        public static string crop_types_6 {
            get {
                return ResourceManager.GetString("crop_types_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alfalfa.
        /// </summary>
        public static string crop_types_7 {
            get {
                return ResourceManager.GetString("crop_types_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avena.
        /// </summary>
        public static string crop_types_8 {
            get {
                return ResourceManager.GetString("crop_types_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajonjolí.
        /// </summary>
        public static string crop_types_9 {
            get {
                return ResourceManager.GetString("crop_types_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciclo.
        /// </summary>
        public static string cycle {
            get {
                return ResourceManager.GetString("cycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diciembre.
        /// </summary>
        public static string december {
            get {
                return ResourceManager.GetString("december", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grados celsius.
        /// </summary>
        public static string degrees_celsius {
            get {
                return ResourceManager.GetString("degrees_celsius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delinear parcela.
        /// </summary>
        public static string deliniate_parcel {
            get {
                return ResourceManager.GetString("deliniate_parcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evapotranspiración diaria cultivo bajo.
        /// </summary>
        public static string desc {
            get {
                return ResourceManager.GetString("desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles.
        /// </summary>
        public static string details {
            get {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evapotranspiración diaria cultivo alto.
        /// </summary>
        public static string detc {
            get {
                return ResourceManager.GetString("detc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperatura alta diaria.
        /// </summary>
        public static string dht {
            get {
                return ResourceManager.GetString("dht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grados en sentido horario desde el norte.
        /// </summary>
        public static string direction_unit {
            get {
                return ResourceManager.GetString("direction_unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to °.
        /// </summary>
        public static string direction_unit_short {
            get {
                return ResourceManager.GetString("direction_unit_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperatura baja diaria.
        /// </summary>
        public static string dlt {
            get {
                return ResourceManager.GetString("dlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precipitación diaria.
        /// </summary>
        public static string dp {
            get {
                return ResourceManager.GetString("dp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radiación solar diaria.
        /// </summary>
        public static string dsr {
            get {
                return ResourceManager.GetString("dsr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fin.
        /// </summary>
        public static string end {
            get {
                return ResourceManager.GetString("end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milímetros por día.
        /// </summary>
        public static string evapotranspiration_unit {
            get {
                return ResourceManager.GetString("evapotranspiration_unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milímetros por hora.
        /// </summary>
        public static string evapotranspiration_unit_hour {
            get {
                return ResourceManager.GetString("evapotranspiration_unit_hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm/h.
        /// </summary>
        public static string evapotranspiration_unit_hour_short {
            get {
                return ResourceManager.GetString("evapotranspiration_unit_hour_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm/día.
        /// </summary>
        public static string evapotranspiration_unit_short {
            get {
                return ResourceManager.GetString("evapotranspiration_unit_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Febrero.
        /// </summary>
        public static string february {
            get {
                return ResourceManager.GetString("february", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtro.
        /// </summary>
        public static string filter {
            get {
                return ResourceManager.GetString("filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrar por ciclo.
        /// </summary>
        public static string filter_cycle {
            get {
                return ResourceManager.GetString("filter_cycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrar por años.
        /// </summary>
        public static string filter_years {
            get {
                return ResourceManager.GetString("filter_years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grados-día de crecimiento.
        /// </summary>
        public static string gdd {
            get {
                return ResourceManager.GetString("gdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punto de rocío por hora.
        /// </summary>
        public static string hd {
            get {
                return ResourceManager.GetString("hd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grados-día de calentamiento.
        /// </summary>
        public static string hdd {
            get {
                return ResourceManager.GetString("hdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evapotranspiración por hora cultivo pequeño.
        /// </summary>
        public static string hesc {
            get {
                return ResourceManager.GetString("hesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evapotranspiración por hora cultivo alto.
        /// </summary>
        public static string hetc {
            get {
                return ResourceManager.GetString("hetc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor ingrese la siguiente información opcional.
        /// </summary>
        public static string hint_additional_information {
            get {
                return ResourceManager.GetString("hint_additional_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione el ciclo agronómico.
        /// </summary>
        public static string hint_agronomical_cycle {
            get {
                return ResourceManager.GetString("hint_agronomical_cycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area estimada de parcela.
        /// </summary>
        public static string hint_area {
            get {
                return ResourceManager.GetString("hint_area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cultivo sembrado.
        /// </summary>
        public static string hint_crop {
            get {
                return ResourceManager.GetString("hint_crop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cultivar.
        /// </summary>
        public static string hint_cultivar {
            get {
                return ResourceManager.GetString("hint_cultivar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cultivar sembrado.
        /// </summary>
        public static string hint_cultivar_placeholder {
            get {
                return ResourceManager.GetString("hint_cultivar_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Apellido.
        /// </summary>
        public static string hint_firstname_lastname {
            get {
                return ResourceManager.GetString("hint_firstname_lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riego.
        /// </summary>
        public static string hint_irrigation {
            get {
                return ResourceManager.GetString("hint_irrigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tienes mensajes no leídos.
        /// </summary>
        public static string hint_notification_received {
            get {
                return ResourceManager.GetString("hint_notification_received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar los mensajes en una lista.
        /// </summary>
        public static string hint_notifications {
            get {
                return ResourceManager.GetString("hint_notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tecnologías usadas.
        /// </summary>
        public static string hint_other_technology_used {
            get {
                return ResourceManager.GetString("hint_other_technology_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de parcela.
        /// </summary>
        public static string hint_parcel_name {
            get {
                return ResourceManager.GetString("hint_parcel_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (para identificación, ej: Maíz Camino 1).
        /// </summary>
        public static string hint_parcel_name_1 {
            get {
                return ResourceManager.GetString("hint_parcel_name_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desempeño.
        /// </summary>
        public static string hint_performance {
            get {
                return ResourceManager.GetString("hint_performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de aplicaicón de pesticida.
        /// </summary>
        public static string hint_pesticide_date {
            get {
                return ResourceManager.GetString("hint_pesticide_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre del pesticida aplicado.
        /// </summary>
        public static string hint_pesticide_product {
            get {
                return ResourceManager.GetString("hint_pesticide_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producto.
        /// </summary>
        public static string hint_pesticide_product_placeholder {
            get {
                return ResourceManager.GetString("hint_pesticide_product_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de siembra.
        /// </summary>
        public static string hint_planting_date {
            get {
                return ResourceManager.GetString("hint_planting_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre del productor.
        /// </summary>
        public static string hint_producer_name {
            get {
                return ResourceManager.GetString("hint_producer_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor seleccione que tecnologías se emplearon:.
        /// </summary>
        public static string hint_technologies_used {
            get {
                return ResourceManager.GetString("hint_technologies_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otras tecnologías.
        /// </summary>
        public static string hint_technology_other {
            get {
                return ResourceManager.GetString("hint_technology_other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se encuentra en su parcela?.
        /// </summary>
        public static string hint_user_at_parcel {
            get {
                return ResourceManager.GetString("hint_user_at_parcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione el año.
        /// </summary>
        public static string hint_year {
            get {
                return ResourceManager.GetString("hint_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vatios por metro cuadrado.
        /// </summary>
        public static string hourly_radiation_unit {
            get {
                return ResourceManager.GetString("hourly_radiation_unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W/m².
        /// </summary>
        public static string hourly_radiation_unit_short {
            get {
                return ResourceManager.GetString("hourly_radiation_unit_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precipitación por hora.
        /// </summary>
        public static string hp {
            get {
                return ResourceManager.GetString("hp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radiación solar por hora.
        /// </summary>
        public static string hsr {
            get {
                return ResourceManager.GetString("hsr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperatura por hora.
        /// </summary>
        public static string ht {
            get {
                return ResourceManager.GetString("ht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centro.
        /// </summary>
        public static string hub {
            get {
                return ResourceManager.GetString("hub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección del viento por hora.
        /// </summary>
        public static string hwd {
            get {
                return ResourceManager.GetString("hwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocidad del viento por hora.
        /// </summary>
        public static string hws {
            get {
                return ResourceManager.GetString("hws", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institución.
        /// </summary>
        public static string institution {
            get {
                return ResourceManager.GetString("institution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irrigado:.
        /// </summary>
        public static string irrigated {
            get {
                return ResourceManager.GetString("irrigated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riego.
        /// </summary>
        public static string irrigation_type_1 {
            get {
                return ResourceManager.GetString("irrigation_type_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riego de punteo.
        /// </summary>
        public static string irrigation_type_2 {
            get {
                return ResourceManager.GetString("irrigation_type_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporal.
        /// </summary>
        public static string irrigation_type_3 {
            get {
                return ResourceManager.GetString("irrigation_type_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enero.
        /// </summary>
        public static string january {
            get {
                return ResourceManager.GetString("january", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Julio.
        /// </summary>
        public static string july {
            get {
                return ResourceManager.GetString("july", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junio.
        /// </summary>
        public static string june {
            get {
                return ResourceManager.GetString("june", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Última Modificación.
        /// </summary>
        public static string last_modification {
            get {
                return ResourceManager.GetString("last_modification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitud.
        /// </summary>
        public static string lat {
            get {
                return ResourceManager.GetString("lat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lng.
        /// </summary>
        public static string lng {
            get {
                return ResourceManager.GetString("lng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargar datos.
        /// </summary>
        public static string load_data {
            get {
                return ResourceManager.GetString("load_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubicación.
        /// </summary>
        public static string location {
            get {
                return ResourceManager.GetString("location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubicación.
        /// </summary>
        public static string location1 {
            get {
                return ResourceManager.GetString("location1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marzo.
        /// </summary>
        public static string march {
            get {
                return ResourceManager.GetString("march", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mayo.
        /// </summary>
        public static string may {
            get {
                return ResourceManager.GetString("may", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milímetros.
        /// </summary>
        public static string millimeters {
            get {
                return ResourceManager.GetString("millimeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm.
        /// </summary>
        public static string millimeters_unit {
            get {
                return ResourceManager.GetString("millimeters_unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noviembre.
        /// </summary>
        public static string november {
            get {
                return ResourceManager.GetString("november", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octubre.
        /// </summary>
        public static string october {
            get {
                return ResourceManager.GetString("october", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vale.
        /// </summary>
        public static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información opcional.
        /// </summary>
        public static string optional_information {
            get {
                return ResourceManager.GetString("optional_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva parcela.
        /// </summary>
        public static string page_title_add_parcel {
            get {
                return ResourceManager.GetString("page_title_add_parcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información comparativa local.
        /// </summary>
        public static string page_title_benchmarking {
            get {
                return ResourceManager.GetString("page_title_benchmarking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enlaces.
        /// </summary>
        public static string page_title_links {
            get {
                return ResourceManager.GetString("page_title_links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingreso.
        /// </summary>
        public static string page_title_login {
            get {
                return ResourceManager.GetString("page_title_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to México Produce!.
        /// </summary>
        public static string page_title_main {
            get {
                return ResourceManager.GetString("page_title_main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapa.
        /// </summary>
        public static string page_title_map {
            get {
                return ResourceManager.GetString("page_title_map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensajes.
        /// </summary>
        public static string page_title_notifications {
            get {
                return ResourceManager.GetString("page_title_notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese información.
        /// </summary>
        public static string page_title_parcel_add_information {
            get {
                return ResourceManager.GetString("page_title_parcel_add_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información comparativa local.
        /// </summary>
        public static string page_title_parcel_benchmarking {
            get {
                return ResourceManager.GetString("page_title_parcel_benchmarking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles.
        /// </summary>
        public static string page_title_parcel_details {
            get {
                return ResourceManager.GetString("page_title_parcel_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información de parcela.
        /// </summary>
        public static string page_title_parcel_page {
            get {
                return ResourceManager.GetString("page_title_parcel_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clima.
        /// </summary>
        public static string page_title_parcel_weather {
            get {
                return ResourceManager.GetString("page_title_parcel_weather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ventanas de oportunidad.
        /// </summary>
        public static string page_title_parcel_windows_of_opportunity {
            get {
                return ResourceManager.GetString("page_title_parcel_windows_of_opportunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcelas.
        /// </summary>
        public static string page_title_parcels_overview {
            get {
                return ResourceManager.GetString("page_title_parcels_overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regístrese.
        /// </summary>
        public static string page_title_register {
            get {
                return ResourceManager.GetString("page_title_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clima.
        /// </summary>
        public static string page_title_weather {
            get {
                return ResourceManager.GetString("page_title_weather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido(a).
        /// </summary>
        public static string page_title_welcome {
            get {
                return ResourceManager.GetString("page_title_welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcelas.
        /// </summary>
        public static string parcels {
            get {
                return ResourceManager.GetString("parcels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terreno.
        /// </summary>
        public static string plot {
            get {
                return ResourceManager.GetString("plot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precipitación.
        /// </summary>
        public static string precipitation {
            get {
                return ResourceManager.GetString("precipitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de produccion.
        /// </summary>
        public static string production_type {
            get {
                return ResourceManager.GetString("production_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megajoules .
        /// </summary>
        public static string radiation_unit {
            get {
                return ResourceManager.GetString("radiation_unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MJ/m.
        /// </summary>
        public static string radiation_unit_short {
            get {
                return ResourceManager.GetString("radiation_unit_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No irrigado:.
        /// </summary>
        public static string rainfed {
            get {
                return ResourceManager.GetString("rainfed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar los datos comparativos.
        /// </summary>
        public static string refresh_benchmarking_data {
            get {
                return ResourceManager.GetString("refresh_benchmarking_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo electrónico.
        /// </summary>
        public static string register_email {
            get {
                return ResourceManager.GetString("register_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor ingrese una dirección de correo electrónico.
        /// </summary>
        public static string register_email_empty {
            get {
                return ResourceManager.GetString("register_email_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor asegúrese de usar una dirección de correo electrónico válida.
        /// </summary>
        public static string register_email_invalid {
            get {
                return ResourceManager.GetString("register_email_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string register_password {
            get {
                return ResourceManager.GetString("register_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor ingrese una contraseña.
        /// </summary>
        public static string register_password_empty {
            get {
                return ResourceManager.GetString("register_password_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifique su contraseña.
        /// </summary>
        public static string register_password_verification {
            get {
                return ResourceManager.GetString("register_password_verification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor verifique su contraseña.
        /// </summary>
        public static string register_password_verification_empty {
            get {
                return ResourceManager.GetString("register_password_verification_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor asegúrese de ingresar la misma contraseña dos veces.
        /// </summary>
        public static string register_password_verification_fail {
            get {
                return ResourceManager.GetString("register_password_verification_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de usuario.
        /// </summary>
        public static string register_username {
            get {
                return ResourceManager.GetString("register_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor ingrese un nombre de usuario.
        /// </summary>
        public static string register_username_empty {
            get {
                return ResourceManager.GetString("register_username_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humedad relativa.
        /// </summary>
        public static string rh {
            get {
                return ResourceManager.GetString("rh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({porcentaje}% completo).
        /// </summary>
        public static string s {
            get {
                return ResourceManager.GetString("s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Septiembre.
        /// </summary>
        public static string september {
            get {
                return ResourceManager.GetString("september", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radiación solar.
        /// </summary>
        public static string solar_radiation {
            get {
                return ResourceManager.GetString("solar_radiation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metros por segundo.
        /// </summary>
        public static string speed_unit {
            get {
                return ResourceManager.GetString("speed_unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m/s.
        /// </summary>
        public static string speed_unit_short {
            get {
                return ResourceManager.GetString("speed_unit_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superficie.
        /// </summary>
        public static string surface {
            get {
                return ResourceManager.GetString("surface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Técnico.
        /// </summary>
        public static string technician {
            get {
                return ResourceManager.GetString("technician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tecnologías que fueron usadas:.
        /// </summary>
        public static string technologies_used {
            get {
                return ResourceManager.GetString("technologies_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambio a variedades mejoradas, nuevas y adaptadas a las zonas con potencial para incrementar el rendimiento .
        /// </summary>
        public static string technology_1 {
            get {
                return ResourceManager.GetString("technology_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpretación y uso del análisis de suelo.
        /// </summary>
        public static string technology_2 {
            get {
                return ResourceManager.GetString("technology_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uso del sensor infrarrojo para fertilización óptima.
        /// </summary>
        public static string technology_3 {
            get {
                return ResourceManager.GetString("technology_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uso de biofertilizantes.
        /// </summary>
        public static string technology_4 {
            get {
                return ResourceManager.GetString("technology_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mejoradores de suelo para complementar fertilización.
        /// </summary>
        public static string technology_5 {
            get {
                return ResourceManager.GetString("technology_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mínimo movimiento de suelo, retención de residuos y rotación de cultivos.
        /// </summary>
        public static string technology_6 {
            get {
                return ResourceManager.GetString("technology_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introducción de nuevos cultivos en la rotación (ejemplo: cultivos de forraje).
        /// </summary>
        public static string technology_7 {
            get {
                return ResourceManager.GetString("technology_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tecnología para mejorar el almacenamiento del grano.
        /// </summary>
        public static string technology_8 {
            get {
                return ResourceManager.GetString("technology_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperatura.
        /// </summary>
        public static string temperature {
            get {
                return ResourceManager.GetString("temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formador.
        /// </summary>
        public static string trainer {
            get {
                return ResourceManager.GetString("trainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidad.
        /// </summary>
        public static string unit {
            get {
                return ResourceManager.GetString("unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to °C.
        /// </summary>
        public static string unit_celsius {
            get {
                return ResourceManager.GetString("unit_celsius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ha].
        /// </summary>
        public static string unit_hectares {
            get {
                return ResourceManager.GetString("unit_hectares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [tons/ha].
        /// </summary>
        public static string unit_performance {
            get {
                return ResourceManager.GetString("unit_performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizar esta ubicación.
        /// </summary>
        public static string use_this_location {
            get {
                return ResourceManager.GetString("use_this_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ver.
        /// </summary>
        public static string view {
            get {
                return ResourceManager.GetString("view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CIMMYT Protocolos del suelo.
        /// </summary>
        public static string weblink1 {
            get {
                return ResourceManager.GetString("weblink1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Como Crecer con Don Crecencio.
        /// </summary>
        public static string weblink2 {
            get {
                return ResourceManager.GetString("weblink2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Año.
        /// </summary>
        public static string year {
            get {
                return ResourceManager.GetString("year", resourceCulture);
            }
        }
    }
}
