//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CimmytApp.Resources.Core.Parcel.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ActivityDetail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ActivityDetail() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CimmytApp.Resources.Core.Parcel.Views.ActivityDetail", typeof(ActivityDetail).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save activity.
        /// </summary>
        internal static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applied products.
        /// </summary>
        internal static string applied_products {
            get {
                return ResourceManager.GetString("applied_products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total cost of the activity ($).
        /// </summary>
        internal static string cost {
            get {
                return ResourceManager.GetString("cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of the activity.
        /// </summary>
        internal static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosage / ha.
        /// </summary>
        internal static string dosis {
            get {
                return ResourceManager.GetString("dosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the activity.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to product obtained.
        /// </summary>
        internal static string product {
            get {
                return ResourceManager.GetString("product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount applied.
        /// </summary>
        internal static string quantity {
            get {
                return ResourceManager.GetString("quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kilograms of seeds.
        /// </summary>
        internal static string seeds_kg {
            get {
                return ResourceManager.GetString("seeds_kg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number of seeds.
        /// </summary>
        internal static string seeds_nr {
            get {
                return ResourceManager.GetString("seeds_nr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variety planted.
        /// </summary>
        internal static string variety {
            get {
                return ResourceManager.GetString("variety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yield.
        /// </summary>
        internal static string yield {
            get {
                return ResourceManager.GetString("yield", resourceCulture);
            }
        }
    }
}
