//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CimmytApp.Resources.Core.Parcel.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ActivityPage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ActivityPage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CimmytApp.Resources.Core.Parcel.Views.ActivityPage", typeof(ActivityPage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercialization.
        /// </summary>
        internal static string commercialization {
            get {
                return ResourceManager.GetString("commercialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weed control.
        /// </summary>
        internal static string deweeding {
            get {
                return ResourceManager.GetString("deweeding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fertilization.
        /// </summary>
        internal static string fertilizer {
            get {
                return ResourceManager.GetString("fertilizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ground preparation.
        /// </summary>
        internal static string ground_preparation {
            get {
                return ResourceManager.GetString("ground_preparation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harvest.
        /// </summary>
        internal static string harvest {
            get {
                return ResourceManager.GetString("harvest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irrigation.
        /// </summary>
        internal static string irrigation {
            get {
                return ResourceManager.GetString("irrigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other activities.
        /// </summary>
        internal static string other_activities {
            get {
                return ResourceManager.GetString("other_activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pest control.
        /// </summary>
        internal static string pest_control {
            get {
                return ResourceManager.GetString("pest_control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post harvest storage.
        /// </summary>
        internal static string post_harvest_storage {
            get {
                return ResourceManager.GetString("post_harvest_storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application of soil improvers.
        /// </summary>
        internal static string soil_improvers {
            get {
                return ResourceManager.GetString("soil_improvers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sowing.
        /// </summary>
        internal static string sowing {
            get {
                return ResourceManager.GetString("sowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add activity to plot.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
    }
}
