//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CimmytApp.Resources.Core.Parcel.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AddParcelPage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AddParcelPage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CimmytApp.Resources.Core.Plot.Views.AddParcelPage", typeof(AddParcelPage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string btn_save_and_new {
            get {
                return ResourceManager.GetString("btn_save_and_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add parcel activities.
        /// </summary>
        internal static string hint_activities {
            get {
                return ResourceManager.GetString("hint_activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose on map.
        /// </summary>
        internal static string hint_choose_location {
            get {
                return ResourceManager.GetString("hint_choose_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of crop.
        /// </summary>
        internal static string hint_crop {
            get {
                return ResourceManager.GetString("hint_crop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use GPS.
        /// </summary>
        internal static string hint_gps_location {
            get {
                return ResourceManager.GetString("hint_gps_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select location of the parcel.
        /// </summary>
        internal static string hint_location {
            get {
                return ResourceManager.GetString("hint_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add parcel management information.
        /// </summary>
        internal static string hint_management_info {
            get {
                return ResourceManager.GetString("hint_management_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot name.
        /// </summary>
        internal static string hint_parcel_name {
            get {
                return ResourceManager.GetString("hint_parcel_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (for identification, for example: Corn 1).
        /// </summary>
        internal static string hint_parcel_name_1 {
            get {
                return ResourceManager.GetString("hint_parcel_name_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of sowing.
        /// </summary>
        internal static string hint_planting_date {
            get {
                return ResourceManager.GetString("hint_planting_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add used technologies.
        /// </summary>
        internal static string hint_technologies {
            get {
                return ResourceManager.GetString("hint_technologies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maturity type of the cultivar.
        /// </summary>
        internal static string madurez {
            get {
                return ResourceManager.GetString("madurez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select.
        /// </summary>
        internal static string select {
            get {
                return ResourceManager.GetString("select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Climate type of the cultivar.
        /// </summary>
        internal static string tipo_clima {
            get {
                return ResourceManager.GetString("tipo_clima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add parcel.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
    }
}
